# Generated by Django 4.1.7 on 2023-11-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='my_advice',
            field=models.BooleanField(default=False),
        ),
    ]
